# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12peer_service.proto\"3\n\x0b\x46ileRequest\x12\x11\n\tpeer_name\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\"#\n\x10\x44ownloadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x0bPeerService\x12/\n\x0c\x44ownloadFile\x12\x0c.FileRequest\x1a\x11.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEREQUEST']._serialized_start=22
  _globals['_FILEREQUEST']._serialized_end=73
  _globals['_DOWNLOADRESPONSE']._serialized_start=75
  _globals['_DOWNLOADRESPONSE']._serialized_end=110
  _globals['_PEERSERVICE']._serialized_start=112
  _globals['_PEERSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
